{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-dwq2
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - qiime2 {{ qiime2_epoch }}
    - q2-types {{ qiime2_epoch }}

test:
  requires:
    - pytest
  imports:
    - q2_dwq2
    - qiime2.plugins.dwq2
  commands:
    - pytest q2_dwq2 --pyargs q2_dwq2

about:
  home: https://cap-lab.bio
  license: BSD-3-Clause
  license_family: BSD
